TOMCAT_VERSION: 8.5.37
TOMCAT_MAJOR_VERSION: "{{ TOMCAT_VERSION.split('.')[0] }}"
TOMCAT_URL: https://archive.apache.org/dist/tomcat/tomcat-{{TOMCAT_MAJOR_VERSION}}/v{{TOMCAT_VERSION}}/bin/apache-tomcat-{{TOMCAT_VERSION}}.tar.gz
APP_USER: student
APP_HOME: "/home/{{APP_USER}}"
